{
 "title": "Vols",
 "time": { "from": "2021-03-13T13:53:42.195Z", "to": "2021-03-13T13:59:00.993Z" },
 "panels": [
  {
   "title": "Map",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "GPS",
     "select": [
      [
       { "params": [ "LatitudeFromGPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*57.2958" ], "type": "math" },
       { "params": [ "Latitude" ], "type": "alias" }
      ],
      [
       { "params": [ "LongitudeFromGPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*57.2958" ], "type": "math" },
       { "params": [ "Longitude" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "rotrpm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ENGINE",
     "query": "SELECT mean(\"EngineRPM\") AS \"Rpm\", mean(\"ManifoldPressure\") *3.6 AS \"GND Vitesse\", FROM \"ENGINE\" WHERE $timeFilter GROUP BY time($__interval) fill(none)\n",
     "select": [
      [
       { "params": [ "EngineRPM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rpm" ], "type": "alias" }
      ],
      [
       { "params": [ "ManifoldPressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*29.53" ], "type": "math" },
       { "params": [ "MAP" ], "type": "alias" }
      ],
      [
       { "params": [ "EngineFuelFlowRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "FuelFlowRate" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pitch / Roll",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 17 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AIRU",
     "select": [
      [
       { "params": [ "PitchAngle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*180/3.1459" ], "type": "math" },
       { "params": [ "Pitch" ], "type": "alias" }
      ],
      [
       { "params": [ "RollAngle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*180/3.1459" ], "type": "math" },
       { "params": [ "Roll" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vertical Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 17 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "AIRU",
     "select": [
      [
       { "params": [ "VerticalSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*3.6" ], "type": "math" },
       { "params": [ "Rotor" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPS Speed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "velocitykmh" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "GPS",
     "select": [
      [
       { "params": [ "GroundSpeedFromGPS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*3.6" ], "type": "math" },
       { "params": [ "GPS Speed" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}